### ISSUE TITLE
I'm not able to use useSt8 with deno and fresh framework.

### ISSUE THREAD

**Issue by renatonmag** [mweststrate/use-st8#21]
This is the error:

```TypeError: Cannot read properties of null (reading 'useState')
    at Object.useState (file:///home/renato/.cache/deno/npm/registry.npmjs.org/react/18.2.0/cjs/react.development.js:1622:21)
    at t (file:///home/renato/.cache/deno/npm/registry.npmjs.org/use-st8/1.1.0/lib/index.js:1:458)
    at Object.Comment (file:///home/renato/Dev/fresh/blog/islands/Comment.tsx:7:19)
    at https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1626
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1653)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:2689)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:2578)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:2689)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)```
    
    Can someone give me some insight? Fresh uses preact.

**Comment by renatonmag** [comment]
I figured out how to use preact-compat. Thanks!
